### ISSUE TITLE
panic on optional positional arguments

### ISSUE THREAD

**Issue by SitiSchu** [TeXitoi/structopt#224]
When using `required = false` on a positional argument and then calling the program without the (optional) argument it will panic with ```thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:347:21```

Code: 
```
use structopt::StructOpt;

#[derive(StructOpt, Debug)]
enum Opt {
    #[structopt(name = "list")]
    List {
        #[structopt(name = "collection", required = false)]
        collection_name: String,
    },
}

fn main() {
    let matches = Opt::from_args();
    println!("{:?}", matches);
}

```

Run with `cargo run -- list`
This will panic on structopt 0.2.18 with 
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:347:21
stack backtrace:
   0:     0x56177ef13303 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h6485381528590a55
                               at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1:     0x56177ef0ee6b - std::sys_common::backtrace::_print::h49a82ae9552e35c7
                               at src/libstd/sys_common/backtrace.rs:71
   2:     0x56177ef12126 - std::panicking::default_hook::{{closure}}::he20974adbefcc046
                               at src/libstd/sys_common/backtrace.rs:59
                               at src/libstd/panicking.rs:197
   3:     0x56177ef11eb9 - std::panicking::default_hook::he4af6af4ac7fef7b
                               at src/libstd/panicking.rs:211
   4:     0x56177ef127cf - std::panicking::rust_panic_with_hook::h057ff03eb4c8000f
                               at src/libstd/panicking.rs:474
   5:     0x56177ef12351 - std::panicking::continue_panic_fmt::ha6d6ae144369025b
                               at src/libstd/panicking.rs:381
   6:     0x56177ef12235 - rust_begin_unwind
                               at src/libstd/panicking.rs:308
   7:     0x56177ef2475c - core::panicking::panic_fmt::hc4f83bfed80aeabd
                               at src/libcore/panicking.rs:85
   8:     0x56177ef2469b - core::panicking::panic::h62fdcfa056e70982
                               at src/libcore/panicking.rs:49
   9:     0x56177ecfc155 - core::option::Option<T>::unwrap::ha1d36af67d24f027
                               at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/macros.rs:12
  10:     0x56177ecfdc92 - tests::Opt::from_subcommand::hcc124b15edc1a428
                               at src/main.rs:3
  11:     0x56177ecfd8d6 - <tests::Opt as structopt::StructOpt>::from_clap::ha1f94c2ff27c8f04
                               at src/main.rs:3
  12:     0x56177ecfe0be - structopt::StructOpt::from_args::h1254a4358771c462
                               at /home/sitischu/.cargo/registry/src/github.com-1ecc6299db9ec823/structopt-0.2.18/src/lib.rs:530
  13:     0x56177ecfd650 - tests::main::h8409f887959f265f
                               at src/main.rs:13
  14:     0x56177ecfe48f - std::rt::lang_start::{{closure}}::hf6c10bd875bc3e44
                               at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  15:     0x56177ef121d2 - std::panicking::try::do_call::hc3d8373a0b215f51
                               at src/libstd/rt.rs:49
                               at src/libstd/panicking.rs:293
  16:     0x56177ef147b9 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:85
  17:     0x56177ef12cdc - std::rt::lang_start_internal::he5218c8b95d395f2
                               at src/libstd/panicking.rs:272
                               at src/libstd/panic.rs:394
                               at src/libstd/rt.rs:48
  18:     0x56177ecfe468 - std::rt::lang_start::h4720851eba028021
                               at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  19:     0x56177ecfdd09 - main
  20:     0x7fe23f5bdb8d - __libc_start_main
  21:     0x56177ecfb169 - _start
                               at ../sysdeps/x86_64/start.S:120
  22:                0x0 - <unknown>
```

**Comment by TeXitoi** [comment]
If you want an optional argument, you can do:
```rust
use structopt::StructOpt;

#[derive(StructOpt, Debug)]
enum Opt {
    #[structopt(name = "list")]
    List {
        #[structopt(name = "collection")]
        collection_name: Option<String>,
        #[structopt(default_value = "this")]
        another: String,
    },
}

fn main() {
    let matches = Opt::from_args();
    println!("{:?}", matches);
}
```

In your example, you remove the requirement, and thus structopt have nothing to put in the `collection_name` variable.

**Comment by SitiSchu** [comment]
Ah, makes sense, thanks

**Comment by SitiSchu** [comment]
Works, thanks again.

**Comment by TeXitoi** [comment]
Welcome
