### ISSUE TITLE
Panic with requires on an argument with underscores

### ISSUE THREAD

**Issue by jeffcutsinger** [TeXitoi/structopt#385]
I have a program with the following (edited down a bit):

```
#[derive(StructOpt, Debug)]
pub struct CommandLine {
  #[structopt(long = "allow-missing-configuration-file", requires = "configuration-file")]
  pub allow_missing_configuration_file: bool,

  #[structopt(long = "configuration-file")]
  pub configuration_file_location: Option<PathBuf>
}
```

Invoking with just `--allow-missing-configuration-file` results in:

```
thread 'main' panicked at 'Fatal internal error. Please consider filing a bug report at https://github.com/clap-rs/clap/issues', src\libcore\option.rs:1185:5
stack backtrace:
...
  13: core::option::expect_failed
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\/src\libcore\option.rs:1185
  14: core::option::Option<alloc::string::String>::expect<alloc::string::String>
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\src\libcore\option.rs:345
  15: clap::app::usage::get_required_usage_from::{{closure}}
             at C:\Users\Jeff\.cargo\registry\src\github.com-1ecc6299db9ec823\clap-2.33.0\src\app\usage.rs:457
  16: core::option::Option<alloc::string::String>::unwrap_or_else<alloc::string::String,closure-18>
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14\src\libcore\option.rs:419
  17: clap::app::usage::get_required_usage_from
             at C:\Users\Jeff\.cargo\registry\src\github.com-1ecc6299db9ec823\clap-2.33.0\src\app\usage.rs:454
  18: clap::app::validator::Validator::missing_required_error
             at C:\Users\Jeff\.cargo\registry\src\github.com-1ecc6299db9ec823\clap-2.33.0\src\app\validator.rs:551
  19: clap::app::validator::Validator::validate_arg_requires<clap::args::arg_builder::flag::FlagBuilder>
             at C:\Users\Jeff\.cargo\registry\src\github.com-1ecc6299db9ec823\clap-2.33.0\src\app\validator.rs:436
  20: clap::app::validator::Validator::validate_matched_args
             at C:\Users\Jeff\.cargo\registry\src\github.com-1ecc6299db9ec823\clap-2.33.0\src\app\validator.rs:288
  21: clap::app::validator::Validator::validate
             at C:\Users\Jeff\.cargo\registry\src\github.com-1ecc6299db9ec823\clap-2.33.0\src\app\validator.rs:77
  22: clap::app::parser::Parser::get_matches_with<mut std::env::ArgsOs*,std::ffi::os_str::OsString>
             at C:\Users\Jeff\.cargo\registry\src\github.com-1ecc6299db9ec823\clap-2.33.0\src\app\parser.rs:1203
  23: clap::app::App::get_matches_from_safe_borrow<mut std::env::ArgsOs*,std::ffi::os_str::OsString>
             at C:\Users\Jeff\.cargo\registry\src\github.com-1ecc6299db9ec823\clap-2.33.0\src\app\mod.rs:1629
  24: clap::app::App::get_matches_from<mut std::env::ArgsOs*,std::ffi::os_str::OsString>
             at C:\Users\Jeff\.cargo\registry\src\github.com-1ecc6299db9ec823\clap-2.33.0\src\app\mod.rs:1509
  25: clap::app::App::get_matches
             at C:\Users\Jeff\.cargo\registry\src\github.com-1ecc6299db9ec823\clap-2.33.0\src\app\mod.rs:1451
  26: structopt::StructOpt::from_args<custode::command_line::CommandLine>
             at C:\Users\Jeff\.cargo\registry\src\github.com-1ecc6299db9ec823\structopt-0.3.14\src\lib.rs:1086
```

I narrowed it down to the fact that `configuration_file_location` has underscores in its name. I also couldn't reproduce the issue with plain clap calls (although maybe I'm not translating accurately enough).

Unit tests:

```
use structopt::StructOpt;
use clap::{App, Arg};

// panics
#[test]
fn requires_argument_with_underscore() {
    #[derive(Debug, PartialEq, StructOpt)]
    pub struct Opt {
        #[structopt(long, requires = "arg_2")]
        pub arg1: Option<i32>,

        #[structopt(long)]
        pub arg_2: Option<i32>
    }

    assert_eq!(Opt { arg1: Some(42), arg_2: Some(43) }, Opt::from_iter(&["test", "--arg1", "42", "--arg_2", "43"]));
    assert_eq!(Opt { arg1: None, arg_2: Some(43) }, Opt::from_iter(&["test", "--arg_2", "43"]));
    assert!(Opt::clap().get_matches_from_safe(&["test", "--arg1", "42"]).is_err());
}

// does not panic
#[test]
fn requires_argument_without_underscore() {
    #[derive(Debug, PartialEq, StructOpt)]
    pub struct Opt {
        #[structopt(long, requires = "arg2")]
        pub arg1: Option<i32>,

        #[structopt(long)]
        pub arg2: Option<i32>
    }

    assert_eq!(Opt { arg1: Some(42), arg2: Some(43) }, Opt::from_iter(&["test", "--arg1", "42", "--arg2", "43"]));
    assert_eq!(Opt { arg1: None, arg2: Some(43) }, Opt::from_iter(&["test", "--arg2", "43"]));
    assert!(Opt::clap().get_matches_from_safe(&["test", "--arg1", "42"]).is_err());
}

//also does not panic
#[test]
fn requires_argument_with_underscore_clap() {
    let app = App::new("Opt")
        .arg(Arg::with_name("arg1")
             .long("arg1")
             .requires("arg_2")
             .takes_value(true))
        .arg(Arg::with_name("arg_2")
             .long("arg_2")
             .takes_value(true));


    assert!(app.get_matches_from_safe(&["test", "--arg1", "42"]).is_err());
}
```

Thanks for this very useful project-- it's made my life much easier. Happy to add additional information if you think it would be helpful.

**Comment by CreepySkeleton** [comment]
This is you're misusing terminology: the name of arg (the string you're passing to `Arg::with_name`) is not the asme as name of long option (`Arg::long`). Argument name serves as an internal id of sorts while long name is just a string. Requires expects this id.

You use `requires = "configuration-file"`, but the _name_ of the arg is `"configuration-file-location"` (renamed name of the field).

Regarding to panic: these massages are really crappy in 2.33 but we managed to improve the situation greatly. Stay tuned for 3.0.

**Comment by jeffcutsinger** [comment]
Please see the attached unit tests which do _not_ have a different name and long option name, but still exhibit this behavior.
