### ISSUE TITLE
Fatal internal error with `requires_if`

### ISSUE THREAD

**Issue by nixpulvis** [TeXitoi/structopt#470]
Getting a panic when I try to use the following structopt definition. Starting with a bug report here before looking into the `clap` output and raising the issue there.

```rust
#[derive(StructOpt, Debug)]
pub struct Cli {
    #[structopt(short = "t", long = "type")]
    ty: SearchType,

    #[structopt(short = "p", long = "population", requires_if("type", "system"))]
    population: u64,
}
```

<details>
<summary>Backtrace</summary>

```
thread 'main' panicked at 'Fatal internal error. Please consider filing a bug report at https://github.com/clap-rs/clap/issues', /home/nixpulvis/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.3/src/app/usage.rs:475:22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/b122908617436af187252572ed5db96850551380/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/b122908617436af187252572ed5db96850551380/library/core/src/panicking.rs:92:14
   2: core::option::expect_failed
             at /rustc/b122908617436af187252572ed5db96850551380/library/core/src/option.rs:1292:5
   3: core::option::Option<T>::expect
             at /home/nixpulvis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:349:21
   4: clap::app::usage::get_required_usage_from::{{closure}}
             at /home/nixpulvis/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.3/src/app/usage.rs:473:17
   5: core::option::Option<T>::unwrap_or_else
             at /home/nixpulvis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:427:21
   6: clap::app::usage::get_required_usage_from
             at /home/nixpulvis/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.3/src/app/usage.rs:470:19
   7: clap::app::usage::create_help_usage
             at /home/nixpulvis/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.3/src/app/usage.rs:72:9
   8: clap::app::usage::create_usage_no_title
             at /home/nixpulvis/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.3/src/app/usage.rs:53:9
   9: clap::app::usage::create_usage_with_title
             at /home/nixpulvis/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.3/src/app/usage.rs:17:22
  10: clap::app::usage::create_error_usage
             at /home/nixpulvis/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.3/src/app/usage.rs:44:5
  11: clap::app::parser::Parser::get_matches_with
             at /home/nixpulvis/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.3/src/app/parser.rs:1174:23
  12: clap::app::parser::Parser::parse_subcommand
             at /home/nixpulvis/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.3/src/app/parser.rs:1382:13
  13: clap::app::parser::Parser::get_matches_with
             at /home/nixpulvis/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.3/src/app/parser.rs:1215:17
  14: clap::app::App::get_matches_from_safe_borrow
             at /home/nixpulvis/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.3/src/app/mod.rs:1639:25
  15: clap::app::App::get_matches_from
             at /home/nixpulvis/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.3/src/app/mod.rs:1519:9
  16: clap::app::App::get_matches
             at /home/nixpulvis/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.3/src/app/mod.rs:1460:9
  17: structopt::StructOpt::from_args
             at /home/nixpulvis/.cargo/registry/src/github.com-1ecc6299db9ec823/structopt-0.3.21/src/lib.rs:1090:26
  18: galos::main::main::{{closure}}
             at ./src/main.rs:127:15
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/nixpulvis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  20: galos::main::{{closure}}
             at ./src/main.rs:125:1
  21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/nixpulvis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  22: <async_std::task::builder::SupportTaskLocals<F> as core::future::future::Future>::poll::{{closure}}
             at /home/nixpulvis/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/builder.rs:199:17
  23: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::{{closure}}
             at /home/nixpulvis/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/task_locals_wrapper.rs:60:13
  24: std::thread::local::LocalKey<T>::try_with
             at /home/nixpulvis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
  25: std::thread::local::LocalKey<T>::with
             at /home/nixpulvis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
  26: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current
             at /home/nixpulvis/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/task_locals_wrapper.rs:55:9
  27: <async_std::task::builder::SupportTaskLocals<F> as core::future::future::Future>::poll
             at /home/nixpulvis/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/builder.rs:197:13
  28: <futures_lite::future::Or<F1,F2> as core::future::future::Future>::poll
             at /home/nixpulvis/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-lite-1.11.3/src/future.rs:526:33
  29: async_executor::Executor::run::{{closure}}
             at /home/nixpulvis/.cargo/registry/src/github.com-1ecc6299db9ec823/async-executor-1.4.0/src/lib.rs:236:9
  30: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/nixpulvis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  31: async_executor::LocalExecutor::run::{{closure}}
             at /home/nixpulvis/.cargo/registry/src/github.com-1ecc6299db9ec823/async-executor-1.4.0/src/lib.rs:437:9
  32: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/nixpulvis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  33: async_io::driver::block_on
             at /home/nixpulvis/.cargo/registry/src/github.com-1ecc6299db9ec823/async-io-1.3.1/src/driver.rs:142:33
  34: async_global_executor::reactor::block_on::{{closure}}
             at /home/nixpulvis/.cargo/registry/src/github.com-1ecc6299db9ec823/async-global-executor-2.0.2/src/reactor.rs:3:18
  35: async_global_executor::reactor::block_on
             at /home/nixpulvis/.cargo/registry/src/github.com-1ecc6299db9ec823/async-global-executor-2.0.2/src/reactor.rs:12:5
  36: async_global_executor::executor::block_on::{{closure}}
             at /home/nixpulvis/.cargo/registry/src/github.com-1ecc6299db9ec823/async-global-executor-2.0.2/src/executor.rs:26:36
  37: std::thread::local::LocalKey<T>::try_with
             at /home/nixpulvis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
  38: std::thread::local::LocalKey<T>::with
             at /home/nixpulvis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
  39: async_global_executor::executor::block_on
             at /home/nixpulvis/.cargo/registry/src/github.com-1ecc6299db9ec823/async-global-executor-2.0.2/src/executor.rs:26:5
  40: async_std::task::builder::Builder::blocking::{{closure}}::{{closure}}
             at /home/nixpulvis/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/builder.rs:171:25
  41: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::{{closure}}
             at /home/nixpulvis/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/task_locals_wrapper.rs:60:13
  42: std::thread::local::LocalKey<T>::try_with
             at /home/nixpulvis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
  43: std::thread::local::LocalKey<T>::with
             at /home/nixpulvis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
  44: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current
             at /home/nixpulvis/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/task_locals_wrapper.rs:55:9
  45: async_std::task::builder::Builder::blocking::{{closure}}
             at /home/nixpulvis/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/builder.rs:168:17
  46: std::thread::local::LocalKey<T>::try_with
             at /home/nixpulvis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
  47: std::thread::local::LocalKey<T>::with
             at /home/nixpulvis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
  48: async_std::task::builder::Builder::blocking
             at /home/nixpulvis/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/builder.rs:161:9
  49: async_std::task::block_on::block_on
             at /home/nixpulvis/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.9.0/src/task/block_on.rs:33:5
  50: galos::main
             at ./src/main.rs:125:1
  51: core::ops::function::FnOnce::call_once
             at /home/nixpulvis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
```

</details>

**Comment by TeXitoi** [comment]
you're refering to a unknow arg system. I suspect you want:

```rust
use structopt::StructOpt;

#[derive(StructOpt, Debug)]
pub struct Cli {
    #[structopt(short = "t", long = "type", requires_if("system", "population"))]
    ty: String,

    #[structopt(short = "p", long = "population")]
    population: Option<u64>,
}

fn main() {
    println!("{:?}", Cli::from_args());
}
```

**Comment by nixpulvis** [comment]
Oh wow, the argument / value ordering is backwards from what I was expecting. I wonder why it was designed like this.

Either way, this is a fatal panic on something that I could see being easily mistaken, perhaps there's a better way to avoid this? A compile time check?

**Comment by nixpulvis** [comment]
Also, I'm not sure how to interpret that code you've written. How can the `val` of `"population"` be equal to the string `"system"`?

**Comment by TeXitoi** [comment]
That's a won't fix in clap 2. Some invalid references panics.

On the ty argument, requires_if(system, population) mean ty=system requires population.

**Comment by nixpulvis** [comment]
> On the ty argument, requires_if(system, population) mean ty=system requires population.

Right, which is why I didn't put it there. Is there a way to express what I'm actually trying to accomplish?

**Comment by TeXitoi** [comment]
I didn't understand what you want, seems that my guess was wrong.

**Comment by TeXitoi** [comment]
Ha my bad, didn't see tour last explanation.

**Comment by TeXitoi** [comment]
I can't find a way to express this.

**Comment by nixpulvis** [comment]
> I can't find a way to express this.

Would you consider this a limitation of structopt or clap? In other words, if one was to try and support this use case would the change be required here, or there?

**Comment by TeXitoi** [comment]
Clap.
